import os
import json
import smtplib
from pathlib import Path
from email.message import EmailMessage

from playwright.sync_api import sync_playwright


FACULTY_PAGE_URL = (
    "https://wd501.myworkdaysite.com/"
    "recruiting/byui/BYU-Idaho_Faculty_Opportunities"
    "?timeType=78f926c7a502100191873747b0010000"
)

BASE_URL = "https://wd501.myworkdaysite.com"

KNOWN_JOBS_FILE = Path("known_jobs.json")


def get_jobs():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()

        jobs_response = None

        def handle_response(response):
            nonlocal jobs_response

            if (
                "/wday/cxs/byui/"
                "BYU-Idaho_Faculty_Opportunities/jobs"
                in response.url
                and response.status == 200
            ):
                jobs_response = response

        page.on("response", handle_response)

        print("Opening BYU-Idaho faculty jobs page...")

        page.goto(
            FACULTY_PAGE_URL,
            wait_until="networkidle",
            timeout=60000,
        )

        page.wait_for_timeout(5000)

        if jobs_response is None:
            browser.close()
            raise RuntimeError(
                "Could not find the Workday jobs response."
            )

        data = jobs_response.json()

        browser.close()

    jobs = []

    for job in data["jobPostings"]:
        job_id = job["bulletFields"][0]

        jobs.append(
            {
                "id": job_id,
                "title": job["title"],
                "location": job["locationsText"],
                "posted": job["postedOn"],
                "posting_end": job["bulletFields"][1],
                "url": BASE_URL + job["externalPath"],
            }
        )

    return jobs


def load_known_jobs():
    if not KNOWN_JOBS_FILE.exists():
        return {}

    with open(KNOWN_JOBS_FILE, "r", encoding="utf-8") as file:
        return json.load(file)


def save_known_jobs(jobs):
    with open(KNOWN_JOBS_FILE, "w", encoding="utf-8") as file:
        json.dump(jobs, file, indent=2)


def send_email(new_jobs):
    gmail_username = os.environ["GMAIL_USERNAME"]
    gmail_password = os.environ["GMAIL_APP_PASSWORD"]

    message = EmailMessage()

    if len(new_jobs) == 1:
        subject = "New BYU-Idaho Faculty Job"
    else:
        subject = f"{len(new_jobs)} New BYU-Idaho Faculty Jobs"

    message["Subject"] = subject
    message["From"] = gmail_username
    message["To"] = gmail_username

    # Plain-text version
    text = "NEW BYU-IDAHO FACULTY JOBS\n\n"

    for job in new_jobs:
        text += f"{job['title']}\n"
        text += f"Job ID: {job['id']}\n"
        text += f"{job['location']}\n"
        text += f"{job['posting_end']}\n"
        text += f"{job['url']}\n"
        text += "\n" + "-" * 70 + "\n\n"

    message.set_content(text)

    # HTML version
    html = """
    <html>
    <body style="font-family: Arial, sans-serif;">
        <h2>BYU-Idaho Faculty Job Alert</h2>
    """

    if len(new_jobs) == 1:
        html += "<p><strong>1 new faculty position was posted.</strong></p>"
    else:
        html += (
            f"<p><strong>{len(new_jobs)} new faculty positions "
            "were posted.</strong></p>"
        )

    for job in new_jobs:
        html += f"""
        <div style="
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 15px;
            margin-bottom: 15px;
        ">
            <h3>{job['title']}</h3>

            <p>
                <strong>Job ID:</strong> {job['id']}<br>
                <strong>Location:</strong> {job['location']}<br>
                <strong>{job['posting_end']}</strong>
            </p>

            <p>
                <a href="{job['url']}">
                    View Job Posting
                </a>
            </p>
        </div>
        """

    html += """
        <p style="color: #777; font-size: 12px;">
            This email was automatically generated by your
            BYU-Idaho Faculty Job Alert.
        </p>
    </body>
    </html>
    """

    message.add_alternative(html, subtype="html")

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(gmail_username, gmail_password)
        smtp.send_message(message)

    print("Email sent successfully!")


def main():
    jobs = get_jobs()

    print(f"Total jobs found: {len(jobs)}")

    known_jobs = load_known_jobs()

    print(f"Previously known jobs: {len(known_jobs)}")

    new_jobs = []

    for job in jobs:
        if job["id"] not in known_jobs:
            new_jobs.append(job)

    print(f"New jobs: {len(new_jobs)}")

    if new_jobs:
        print()
        print("NEW JOBS:")
        print("=" * 80)

        for job in new_jobs:
            print()
            print(job["title"])
            print(job["id"])
            print(job["posting_end"])
            print(job["url"])

        send_email(new_jobs)

    else:
        print("No new jobs. No email will be sent.")

    # Save the current jobs
    all_known_jobs = {}

    for job in jobs:
        all_known_jobs[job["id"]] = job

    save_known_jobs(all_known_jobs)

    print(f"Saved {len(all_known_jobs)} jobs.")


if __name__ == "__main__":
    main()
